### ISSUE TITLE
Make the frontend usable. Just add some minimal interface.

### ISSUE THREAD

**Issue by ghoshbishakh** [divyanshumehta/MKT_Quiz#4]
No need for styling, but please add some proper tags like h1 h2 button p etc...

**Comment by ghoshbishakh** [comment]
And on what ground did you close it?

**Comment by divyanshumehta** [comment]
I m sorry. I actually i have just added support for bootstrap and added a top nav bar. Will work on the front end more.

**Comment by ghoshbishakh** [comment]
No I am not talking about the changes. It is just that you need to put
better commit messages and link them to github as well. And make the
changes granular that is for example you changed two things in the last
commit. You could have made two commits for them. And use "fixed #4' phrase
in your commit messages to link them in github automatically
